global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Torus Indexers
  - job_name: 'torus-balance-transfers'
    static_configs:
      - targets: ['host.docker.internal:9101']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'torus-balance-series'
    static_configs:
      - targets: ['host.docker.internal:9102']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'torus-money-flow'
    static_configs:
      - targets: ['host.docker.internal:9103']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'torus-block-stream'
    static_configs:
      - targets: ['host.docker.internal:9104']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  # Torus APIs
  - job_name: 'torus-api'
    static_configs:
      - targets: ['host.docker.internal:9200']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'torus-block-stream-api'
    static_configs:
      - targets: ['host.docker.internal:9201']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'torus-mcp-server'
    static_configs:
      - targets: ['host.docker.internal:9202']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']